FROM docker.n8n.io/n8nio/n8n

# RUN apk update \
#    && apk add --no-cache \
#    jq vim wget unzip ca-certificates procps curl build-base git

# USER root

# RUN npm install -g n8n

# app login: eaf@eaf.com // N8n..Eaf

COPY ./.bashrc /root/.bashrc

# CMD ["n8n"]